version: '3.8'
services:
  automation_backend:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'gunicorn --bind 0.0.0.0:8000 --workers 4 --threads 8 --timeout 120 --preload elarian_py.wsgi'
    ports:
      - "8000:8000"
    volumes:
      - .:/app
