# Generated by Django 3.2.9 on 2021-11-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kra_pin', models.CharField(blank=True, max_length=20, null=True)),
                ('filed', models.BooleanField(default=False)),
            ],
        ),
    ]
